name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Display Go version
        run: go version

      - name: Build
        run: go build -o ./bin/tlsgen-dev